name: Build, Test, and Publish

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - '.github/workflows/**'
      - 'VERSION'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, worker, frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python for backend and worker
        if: matrix.service == 'backend' || matrix.service == 'worker'
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies for backend and worker
        if: matrix.service == 'backend' || matrix.service == 'worker'
        run: |
          pip install -r app/${{ matrix.service }}/src/requirements.txt -r app/${{ matrix.service }}/src/requirements-dev.txt

      - name: Run Python tests
        if: matrix.service == 'backend' || matrix.service == 'worker'
        env:
          AWS_DEFAULT_REGION: "us-east-1"
        run: pytest app/${{ matrix.service }}/src/

      - name: Set up Node.js for frontend
        if: matrix.service == 'frontend'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Node.js dependencies for frontend
        if: matrix.service == 'frontend'
        run: npm install --prefix app/frontend

      - name: Run Node.js tests
        if: matrix.service == 'frontend'
        run: npm test --prefix app/frontend

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend, worker]
    steps:
      - uses: actions/checkout@v4

      - name: Read version
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Versioned Image
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: ./app/${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/study-buddy-${{ matrix.service }}:${{ env.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/study-buddy-${{ matrix.service }}:latest

      - name: Snyk Scan
        uses: snyk/actions/docker@master
        with:
          image: ${{ secrets.DOCKERHUB_USERNAME }}/study-buddy-${{ matrix.service }}:${{ env.VERSION }}
          args: --file=app/${{ matrix.service }}/Dockerfile
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
